# rag-hnsw/docker-compose.yml

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
        env_file:
            - .env
        environment:
            - PYTHONPATH=/app:${PYTHONPATH:-}
            - TZ=Asia/Tokyo
            - BACKEND_URL=ws://backend:8001
        volumes:
            - ./frontend:/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8000:8000"
        depends_on:
            - backend
        networks:
            - app_network
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    backend:
        container_name: backend
        build:
            context: ./backend
        env_file:
            - .env
        environment:
            - PYTHONPATH=/app:${PYTHONPATH:-}
            - TZ=Asia/Tokyo
        volumes:
            - ./backend:/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8001:8001"
        depends_on:
            - aurora
        networks:
            - app_network
        command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

    batch:
        container_name: batch
        build:
            context: ./batch
        env_file:
            - .env
        environment:
            - PYTHONPATH=/app:${PYTHONPATH:-}
            - TZ=Asia/Tokyo
        volumes:
            - ./batch:/app
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8002:8002"
        depends_on:
            - aurora
        networks:
            - app_network
        command: tail -f /dev/null

    aurora:
        container_name: aurora
        build:
            context: ./aurora
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGTZ=Asia/Tokyo
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    pg_data:
